apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: golang-micros
  namespace: argocd
spec:
  description: Project for golang-k8s-microservices applications
  sourceRepos:
    - '*'
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: payment-service-namespace
      server: https://kubernetes.default.svc
    - namespace: inventory-service-namespace
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
