replicaCount: 1
appname:
    name: payment-service
    paymentservicens: payment-service-namespace
image:
  repository: payment-service
  tag: "2.4.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8112

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"

secrets:
  mysqlUser: "dosql12816677"
  mysqlPassword: "wedMGD5e1vdo"
