apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices-root
  namespace: argocd
spec:
  project: microservices
  source:
    repoURL: https://github.com/REPLACE_ME/golang-k8s-microservices.git
    targetRevision: main
    path: argocd/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
