apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appname.name }}-config
  namespace: {{ .Values.appname.paymentservicens }}
data:
  MYSQL_HOST: dosql12.freesqldatabase.com
  MYSQL_PORT: "3306"
  MYSQL_DB: dosql12816677
  MYSQL_PARAMS: "parseTime=true"
