apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.appname.name }}-config
  namespace: {{ .Values.appname.paymentservicens }}
data:
  MYSQL_HOST: mysql-2e9fea2e-dkgosql.a.aivencloud.com
  MYSQL_PORT: "10473"
  MYSQL_DB: defaultdb
  MYSQL_PARAMS: "parseTime=true"
  MYSQL_DBPEM: "certdbmysql/ca.pem"
